encoder: chunk_conformer
encoder_conf:
      activation_type: swish
      time_reduction_factor: 2
      embed_vgg_like: false
      subsampling_factor: 4
      linear_units: 1024
      output_size: 256
      attention_heads: 4
      dropout_rate: 0.1
      positional_dropout_rate: 0.1
      attention_dropout_rate: 0.1
      cnn_module_kernel: 31
      num_blocks: 15    

# decoder related
rnnt_decoder: rnnt
rnnt_decoder_conf:
    embed_size: 256
    hidden_size: 256
    embed_dropout_rate: 0.1
    dropout_rate: 0.2
    use_embed_mask: true

joint_network_conf:
    joint_space_size: 320


# frontend related
frontend: wav_frontend
frontend_conf:
    fs: 16000
    window: hamming
    n_mels: 80
    frame_length: 25
    frame_shift: 10
    lfr_m: 1
    lfr_n: 1
 
# Auxiliary CTC
model: rnnt
model_conf:
    auxiliary_ctc_weight: 0.3

# minibatch related
use_amp: true

# optimization related
accum_grad: 8
grad_clip: 5
max_epoch: 200
val_scheduler_criterion:
    - valid
    - loss
best_model_criterion:
-   - valid
    - cer_transducer
    - min
keep_nbest_models: 10

optim: adam
optim_conf:
   lr: 0.002
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 25000

normalize: None

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0
    - 0.05
    num_time_mask: 5

dataset_conf:
    shuffle: True
    shuffle_conf:
        shuffle_size: 1024
        sort_size: 500
    batch_conf:
        batch_type: token
        batch_size: 5000
    num_workers: 8

log_interval: 50
