name: FunASR Unit Test
run-name: ${{ github.actor }} is testing out FunASR Unit Test 🚀
on:
  pull_request:
      branches:
        - main
  push:
    branches:
      - dev_jy

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]

    steps:
      - name: Remove unnecessary files
        run:
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio
          pip install "modelscope[audio_asr]" --upgrade -f \
            https://modelscope.oss-cn-beijing.aliyuncs.com/releases/repo.html
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e ./
      - name: Testing
        run:
          python tests/run_test.py